# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer_1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1404, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.state = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.state.sizePolicy().hasHeightForWidth())
        self.state.setSizePolicy(sizePolicy)
        self.state.setStyleSheet("font: 14pt \"Agency FB\";")
        self.state.setAlignment(QtCore.Qt.AlignCenter)
        self.state.setObjectName("state")
        self.gridLayout.addWidget(self.state, 6, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OG_IMAGE = QtWidgets.QLabel(self.centralwidget)
        self.OG_IMAGE.setText("")
        self.OG_IMAGE.setObjectName("OG_IMAGE")
        self.horizontalLayout_2.addWidget(self.OG_IMAGE)
        self.MASK_IMAGE = QtWidgets.QLabel(self.centralwidget)
        self.MASK_IMAGE.setText("")
        self.MASK_IMAGE.setObjectName("MASK_IMAGE")
        self.horizontalLayout_2.addWidget(self.MASK_IMAGE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.image_slider = QtWidgets.QScrollBar(self.centralwidget)
        self.image_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_slider.setObjectName("image_slider")
        self.verticalLayout_2.addWidget(self.image_slider)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 5, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.INPUT_TYPE = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.INPUT_TYPE.sizePolicy().hasHeightForWidth())
        self.INPUT_TYPE.setSizePolicy(sizePolicy)
        self.INPUT_TYPE.setObjectName("INPUT_TYPE")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.INPUT_TYPE)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.TDM_INPUT = QtWidgets.QRadioButton(self.INPUT_TYPE)
        self.TDM_INPUT.setChecked(True)
        self.TDM_INPUT.setObjectName("TDM_INPUT")
        self.horizontalLayout_7.addWidget(self.TDM_INPUT)
        self.DICOM_INPUT = QtWidgets.QRadioButton(self.INPUT_TYPE)
        self.DICOM_INPUT.setObjectName("DICOM_INPUT")
        self.horizontalLayout_7.addWidget(self.DICOM_INPUT)
        self.NPY_INPUT = QtWidgets.QRadioButton(self.INPUT_TYPE)
        self.NPY_INPUT.setObjectName("NPY_INPUT")
        self.horizontalLayout_7.addWidget(self.NPY_INPUT)
        self.horizontalLayout.addWidget(self.INPUT_TYPE)
        self.MASK_TYPE = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MASK_TYPE.sizePolicy().hasHeightForWidth())
        self.MASK_TYPE.setSizePolicy(sizePolicy)
        self.MASK_TYPE.setObjectName("MASK_TYPE")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.MASK_TYPE)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.FRANGI = QtWidgets.QRadioButton(self.MASK_TYPE)
        self.FRANGI.setChecked(True)
        self.FRANGI.setObjectName("FRANGI")
        self.horizontalLayout_8.addWidget(self.FRANGI)
        self.NO_FRANGI = QtWidgets.QRadioButton(self.MASK_TYPE)
        self.NO_FRANGI.setChecked(False)
        self.NO_FRANGI.setObjectName("NO_FRANGI")
        self.horizontalLayout_8.addWidget(self.NO_FRANGI)
        self.horizontalLayout.addWidget(self.MASK_TYPE)
        self.DICE = QtWidgets.QLabel(self.centralwidget)
        self.DICE.setStyleSheet("font: 22pt \"Agency FB\";")
        self.DICE.setObjectName("DICE")
        self.horizontalLayout.addWidget(self.DICE)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.RESET = QtWidgets.QPushButton(self.centralwidget)
        self.RESET.setObjectName("RESET")
        self.horizontalLayout.addWidget(self.RESET)
        self.CLOSE = QtWidgets.QPushButton(self.centralwidget)
        self.CLOSE.setObjectName("CLOSE")
        self.horizontalLayout.addWidget(self.CLOSE)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LOAD_DATA = QtWidgets.QPushButton(self.centralwidget)
        self.LOAD_DATA.setObjectName("LOAD_DATA")
        self.horizontalLayout_4.addWidget(self.LOAD_DATA)
        self.TEST = QtWidgets.QPushButton(self.centralwidget)
        self.TEST.setObjectName("TEST")
        self.horizontalLayout_4.addWidget(self.TEST)
        self.VESSELRENDER = QtWidgets.QPushButton(self.centralwidget)
        self.VESSELRENDER.setObjectName("VESSELRENDER")
        self.horizontalLayout_4.addWidget(self.VESSELRENDER)
        self.RENDER_WITH_G = QtWidgets.QPushButton(self.centralwidget)
        self.RENDER_WITH_G.setObjectName("RENDER_WITH_G")
        self.horizontalLayout_4.addWidget(self.RENDER_WITH_G)
        self.SAVE_RESULT = QtWidgets.QPushButton(self.centralwidget)
        self.SAVE_RESULT.setObjectName("SAVE_RESULT")
        self.horizontalLayout_4.addWidget(self.SAVE_RESULT)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.state.setText(_translate("MainWindow", "0"))
        self.INPUT_TYPE.setTitle(_translate("MainWindow", "Input Image Type"))
        self.TDM_INPUT.setText(_translate("MainWindow", "TDM"))
        self.DICOM_INPUT.setText(_translate("MainWindow", "Dicom"))
        self.NPY_INPUT.setText(_translate("MainWindow", ".npy"))
        self.MASK_TYPE.setTitle(_translate("MainWindow", "Frangi Filter"))
        self.FRANGI.setText(_translate("MainWindow", "Frangi"))
        self.NO_FRANGI.setText(_translate("MainWindow", "No Frangi"))
        self.DICE.setText(_translate("MainWindow", "Dice : "))
        self.RESET.setText(_translate("MainWindow", "Reset"))
        self.CLOSE.setText(_translate("MainWindow", "Close"))
        self.LOAD_DATA.setText(_translate("MainWindow", "Load Data"))
        self.TEST.setText(_translate("MainWindow", "Testing"))
        self.VESSELRENDER.setText(_translate("MainWindow", "Vessel Render"))
        self.RENDER_WITH_G.setText(_translate("MainWindow", "Vessel Render with Ground Ture"))
        self.SAVE_RESULT.setText(_translate("MainWindow", "Save Result"))

